import React from 'react';
import { TemplateComponentProps } from '@/types/template';
import EditableField from '../dashboard/EditableField';
import { useEditing } from '../dashboard/TemplateEditor';

export const metadata = {
  key: 'aurora',
  title: 'Aurora',
  description: 'Single-column, modern resume with bold header, subtle accents and timeline-style experience.',
  author: 'Generated by Assistant',
  authorUrl: '',
  thumbnail: '',
  tags: ['single-column', 'modern', 'timeline'],
};

export default function AuroraTemplate({ resume, className = '' }: TemplateComponentProps) {
  // Check for editing context
  let editingContext = null;
  try {
    editingContext = useEditing();
  } catch {
    // Not in editing mode
  }
  const isEditMode = editingContext?.isEditMode;

  const contact = resume.contact || {};
  const fmtRange = (s?: string, e?: string) => {
    if (!s && !e) return '';
    if (s && !e) return `${s} — Present`;
    return `${s ?? ''} — ${e ?? ''}`;
  };

  return (
    <div id="resume-preview" className={`max-w-[780px] mx-auto bg-white text-slate-900 ${className}`}>
      {/* Header */}
      <header className="p-8 border-b border-slate-100">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <EditableField field="name" as="h1" className="text-3xl font-extrabold tracking-tight" fallback="Full Name" />
            <EditableField field="title" as="div" className="text-slate-600 mt-1" fallback="Professional Title" />
          </div>

          <div className="text-sm text-slate-600 flex flex-col sm:items-end gap-1">
            {contact.website && <a href={contact.website} target="_blank" rel="noreferrer" className="underline text-sky-600">{contact.website}</a>}
            {contact.email && <a href={`mailto:${contact.email}`}>{contact.email}</a>}
            {contact.phone && <div>{contact.phone}</div>}
            {contact.location && <div>{contact.location}</div>}
          </div>
        </div>
      </header>

      <main className="p-8 space-y-6">
        {/* Summary */}
        <section>
          <h2 className="text-sm font-semibold text-slate-700">Summary</h2>
          <EditableField
            field="summary"
            as="p"
            className="mt-2 text-sm text-slate-700 leading-relaxed"
            fallback="Concise summary that highlights core strengths, focus areas, and impact."
            multiline
          />
        </section>

        {/* Skills */}
        <section>
          <h2 className="text-sm font-semibold text-slate-700">Skills</h2>
          <div className="mt-3 flex flex-wrap gap-2">
            {(resume.skills && resume.skills.length > 0) ? (
              resume.skills.map((s, i) => (
                <span key={i} className="text-xs px-2 py-1 bg-slate-100 rounded">{s}</span>
              ))
            ) : (
              <>
                <span className="text-xs px-2 py-1 bg-slate-100 rounded">JavaScript</span>
                <span className="text-xs px-2 py-1 bg-slate-100 rounded">TypeScript</span>
                <span className="text-xs px-2 py-1 bg-slate-100 rounded">React</span>
              </>
            )}
          </div>
        </section>

        {/* Experience (timeline style) */}
        <section>
          <h2 className="text-sm font-semibold text-slate-700">Experience</h2>
          <div className="mt-4 space-y-6">
            {(resume.experience && resume.experience.length > 0) ? resume.experience.map((ex) => (
              <div key={ex.id} className="relative pl-8">
                <div className="absolute left-0 top-1 w-2 h-2 rounded-full bg-sky-600" />
                <div className="absolute left-1 top-4 h-full w-[2px] bg-slate-100" />
                <div className="flex items-start justify-between">
                  <div>
                    <div className="font-medium text-slate-900">{ex.role || 'Role'} <span className="text-slate-500">— {ex.company || 'Company'}</span></div>
                    {ex.location && <div className="text-xs text-slate-500">{ex.location}</div>}
                  </div>
                  <div className="text-xs text-slate-500">{fmtRange(ex.start, ex.end)}</div>
                </div>
                {ex.bullets && ex.bullets.length > 0 && (
                  <ul className="mt-2 list-disc list-inside text-sm text-slate-700">
                    {ex.bullets.map((b, i) => <li key={i}>{b}</li>)}
                  </ul>
                )}
              </div>
            )) : (
              <div className="text-sm text-slate-600">No experience added yet.</div>
            )}
          </div>
        </section>

        {/* Projects */}
        <section>
          <h2 className="text-sm font-semibold text-slate-700">Projects</h2>
          <div className="mt-3 space-y-3">
            {(resume.sections || []).filter(s => s.type === 'projects').flatMap(s => s.items || []).length > 0 ? (
              (resume.sections || []).filter(s => s.type === 'projects').flatMap(s => s.items || []).map((p: any, i: number) => (
                <div key={i} className="p-3 border rounded bg-slate-50">
                  <div className="flex items-center justify-between">
                    <div className="font-medium">{p.title || p.name || 'Project'}</div>
                    {p.link && <a href={p.link} target="_blank" rel="noreferrer" className="text-xs text-sky-600 underline">View</a>}
                  </div>
                  {p.description && <div className="text-sm text-slate-700 mt-2">{p.description}</div>}
                </div>
              ))
            ) : (
              <div className="text-sm text-slate-600">No projects listed.</div>
            )}
          </div>
        </section>

        {/* Education & Certifications */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <section className="p-4 border rounded">
            <h3 className="text-sm font-semibold text-slate-700">Education</h3>
            <div className="mt-3 space-y-3 text-sm text-slate-700">
              {(resume.education || []).length > 0 ? (resume.education || []).map((ed) => (
                <div key={ed.id}>
                  <div className="font-medium">{ed.school || 'School'}</div>
                  <div className="text-xs text-slate-500">{fmtRange(ed.start, ed.end)} {ed.degree ? `• ${ed.degree}` : ''}</div>
                </div>
              )) : <div className="text-sm text-slate-600">No education entries yet.</div>}
            </div>
          </section>

          <section className="p-4 border rounded">
            <h3 className="text-sm font-semibold text-slate-700">Certifications</h3>
            <div className="mt-3 text-sm text-slate-700">
              {(resume.sections || []).filter(s => s.type === 'certifications').flatMap(s => s.items || []).length > 0 ? (
                (resume.sections || []).filter(s => s.type === 'certifications').flatMap(s => s.items || []).map((c: any, i: number) => (
                  <div key={i} className="py-1">{c}</div>
                ))
              ) : <div className="text-sm text-slate-600">No certifications listed.</div>}
            </div>
          </section>
        </div>

        {/* Footer */}
        <footer className="text-xs text-slate-400 pt-4 border-t">
          <div className="flex items-center justify-between">
            <div>Generated with Aurora template</div>
            <div>{metadata.author}</div>
          </div>
        </footer>
      </main>
    </div>
  );
}
